import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>iqiaoxin</title>
        <meta name="description" content="Generated by create next app" />
        {/* {
          process.env.NODE_ENV === 'production' && 
          <meta httpEquiv="Content-Security-Policy"
            content="default-src 'self'; img-src https://*; child-src 'none';" />
        } */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Iqiaoxin.life!
        </h1>
      </main>

      <footer className={styles.footer}>
        <a className="text-color" href="https://beian.miit.gov.cn" target="_blank" rel="noreferrer">京ICP备2021040357号-1</a>
      </footer>
    </div>
  )
}

export default Home
