import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>iqiaoxin</title>
        <meta name="description" content="Generated by create next app" />
        {/* {
          process.env.NODE_ENV === 'production' && 
          <meta httpEquiv="Content-Security-Policy"
            content="default-src 'self'; img-src https://*; child-src 'none';" />
        } */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Iqiaoxin.life!
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} &nbsp;
            <span>
              <Image src="/LOVE.png" alt="Vercel Logo" width={22} height={19} />
            </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
